<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EcoPause.HardwareHost.Protocol\EcoPause.HardwareHost.Protocol.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>AFKPowerSaver.HardwareHost.Transport</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
