<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EcoPause.Hardware.Abstractions\EcoPause.Hardware.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>AFKPowerSaver.Desktop.Safety</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
