<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EcoPause.Core\EcoPause.Core.csproj" />
    <ProjectReference Include="..\EcoPause.LiveCanary.Model\EcoPause.LiveCanary.Model.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyName>AFKPowerSaver.Hardware.Nvidia.Control</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

</Project>
